#!/bin/bash


echo "NQUEEN SOLUTIONS NODES BLOCKUSED QUEUEUSED MAXBLOCK MAXQUEUE L1 L2 TIME" > res10;
echo "NQUEEN SOLUTIONS NODES BLOCKUSED QUEUEUSED MAXBLOCK MAXQUEUE L1 L2 TIME" > res11;
echo "NQUEEN SOLUTIONS NODES BLOCKUSED QUEUEUSED MAXBLOCK MAXQUEUE L1 L2 TIME" > res12;


START=0;
BLOCK=60000;
QUEUE=60000;



QUEEN=10;

for ((BLOCK=1; BLOCK < 10000; BLOCK=BLOCK*2)); do
	./RCUDA2 -n $QUEEN -l 4 -k 6 -q $QUEUE -b $BLOCK -f >> res10;
done;

QUEEN=11;

for ((BLOCK=1; BLOCK < 10000; BLOCK=BLOCK*2)); do
	./RCUDA2 -n $QUEEN -l 4 -k 6 -q $QUEUE -b $BLOCK -f >> res11;
done;

QUEEN=12;

for ((BLOCK=1; BLOCK < 10000; BLOCK=BLOCK*2)); do
	./RCUDA2 -n $QUEEN -l 4 -k 6 -q $QUEUE -b $BLOCK -f >> res12;
done;

